matrix:
  VERSION:
    - "2.0"
    - "2.1.1"

publish:
  docker:
    file: "$$VERSION/Dockerfile"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/logstash
    tag: $$VERSION
    force_tag: true
    storage_driver: overlay
